//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valdo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_agunan
    {
        public string agunan_id { get; set; }
        public string account_no { get; set; }
        public string customer_id { get; set; }
        public string type { get; set; }
        public decimal amount { get; set; }
    }
}
